# Generated by Django 2.2.28 on 2022-10-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressriafgmlocl'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressriafgmlocl',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
